module.exports = () => {
    const LANGUAGE = 'fieldtrip';
    const newline = '\n';

    function writePreamble(){
      return `% Code generated by GiraffeTools`
    }

    function writeNodes(nodes, links){
      let code = "";
      code += nodes.map(node => {
        let ft_code = "";
        ft_code += "cfg = [];" + newline;
        // #TODO add in parameters
        ft_code += `${node.name}(cfg);`

        return ft_code;
      }).join('\r\n');
      return code;
    }

    function writePostamble() {
      return "% end of script"
    }

    async function writeCode(nodes, links) {
        const preamble = writePreamble();
        const nodeCode = writeNodes(nodes, links);
        const postAmble = writePostamble();
        return [preamble, nodeCode, postAmble].join('\r\n');
    }

    async function writeFiles(nodes, links) {
        const fieldtripFilename = 'GIRAFFE/code/fieldtrip.m';
        return {
            [fieldtripFilename]: await writeCode(nodes)
        }
    }

    return {
        writeCode,
        writeFiles,
    }
}
